### ISSUE TITLE
Incorrect directory separator in Unix for new data

### ISSUE THREAD

**Issue by JoshuaArking** [brent-stone/CAN_Reverse_Engineering#1]
In fileboi.py line 67, `\\` is used as the directory separator between the `Samples` directory and the `loggerProgram0.log`, resulting in FileNotFoundError on Unix systems.

`FileNotFoundError: [Errno 2] File b'/home/joshua/git-repos/CAN_Reverse_Engineering/Pipeline_multi-file/Captures/Make/Model/ModelYear/Samples\\loggerProgram0.log' does not exist: b'/home/joshua/git-repos/CAN_Reverse_Engineering/Pipeline_multi-file/Captures/Make/Model/ModelYear/Samples\\loggerProgram0.log'`

If using valid pickled data instead of new data, this error does not occur. Changing the directory separator to `/` fixes the issue.

**Comment by brent-stone** [comment]
Nice catch Joshua. Changed it from "\\" to "/". Code seems to still run fine on my Windows machine.

Let me know if that fix runs on your Unix computer.

**Comment by JoshuaArking** [comment]
Yes, that fixes it. Thanks!
