### ISSUE TITLE
File mentioned in README.md not found

### ISSUE THREAD

**Issue by wbw60** [brent-stone/CAN_Reverse_Engineering#5]
I cannot locate the home.py file mentioned in the README. md file. Is there a site I need to go to and download the file? In addition the rEDM link in README.md is broken. Which rEDM from github should be used with this software (hay0e/rEDM, SugihariLab/rEDM, cran/rEDM, ??)? Thanks in advance.

Regards

**Comment by brent-stone** [comment]
Thank you for the catch! This should have read main.py in the readme. I edited from my phone so if I missed something please re-open.

**Comment by wbw60** [comment]
Brent, 
  Thanks for the update. Can you tell me which rEDM I should be using? The https://cran.r-project.org/web/packages/rEDM/vignettes/rEDM-tutorial.html link  in the README is broken. Thanks much.
